In [31]:
import pandas as pd

# Load dataset
test_data = pd.read_csv("/content/drive/MyDrive/ML_projects/ENERGY_CONSUMPTION_PREDICTION_USING_AUTOGLUON/datasets/test_energy_data.csv")
train_data = pd.read_csv("/content/drive/MyDrive/ML_projects/ENERGY_CONSUMPTION_PREDICTION_USING_AUTOGLUON/datasets/train_energy_data.csv")

# Inspect columns
print(train_data.head())
print(test_data.head())
print("---------------------------------------------------------------------")
print("train data shape:",train_data.shape)
print("test data shape:",test_data.shape)

  Building Type  Square Footage  Number of Occupants  Appliances Used  \
0   Residential            7063                   76               10
1    Commercial           44372                   66               45
2    Industrial           19255                   37               17
3   Residential           13265                   14               41
4    Commercial           13375                   26               18

   Average Temperature Day of Week  Energy Consumption
0                29.84     Weekday             2713.95
1                16.72     Weekday             5744.99
2                14.30     Weekend             4101.24
3                32.82     Weekday             3009.14
4                11.92     Weekday             3279.17
  Building Type  Square Footage  Number of Occupants  Appliances Used  \
0   Residential           24563                   15                4
1    Commercial           27583                   56               23
2    Commercial           45313                    4               44
3   Residential           41625                   84               17
4   Residential           36720                   58               47

   Average Temperature Day of Week  Energy Consumption
0                28.52     Weekday             2865.57
1                23.07     Weekend             4283.80
2                33.56     Weekday             5067.83
3                27.39     Weekend             4624.30
4                17.08     Weekday             4820.59
---------------------------------------------------------------------
train data shape: (1000, 7)
test data shape: (100, 7)

In [6]:
import shutil
import os
# Define the path to the folder to be deleted
folder_to_delete = '/content/sample_data'

# Check if the folder exists before attempting to delete
if os.path.exists(folder_to_delete):
    shutil.rmtree(folder_to_delete)
    print(f"Folder '{folder_to_delete}' deleted successfully.")
else:
    print(f"Folder '{folder_to_delete}' does not exist.")

Folder '/content/sample_data' deleted successfully.

In [8]:
test_data.isnull().sum()

Building Type          0
Square Footage         0
Number of Occupants    0
Appliances Used        0
Average Temperature    0
Day of Week            0
Energy Consumption     0
dtype: int64

In [9]:
!pip install autogluon.tabular

Collecting autogluon.tabular
  Downloading autogluon_tabular-1.5.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: numpy<2.4.0,>=1.25.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular) (2.0.2)
Requirement already satisfied: scipy<1.17,>=1.5.4 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular) (1.16.3)
Requirement already satisfied: pandas<2.4.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular) (2.2.2)
Requirement already satisfied: scikit-learn<1.8.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular) (1.6.1)
Requirement already satisfied: networkx<4,>=3.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.tabular) (3.6.1)
Collecting autogluon.core==1.5.0 (from autogluon.tabular)
  Downloading autogluon_core-1.5.0-py3-none-any.whl.metadata (13 kB)
Collecting autogluon.features==1.5.0 (from autogluon.tabular)
  Downloading autogluon_features-1.5.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: tqdm<5,>=4.38 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.tabular) (4.67.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.tabular) (2.32.4)
Requirement already satisfied: matplotlib<3.11,>=3.7.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.core==1.5.0->autogluon.tabular) (3.10.0)
Collecting boto3<2,>=1.10 (from autogluon.core==1.5.0->autogluon.tabular)
  Downloading boto3-1.43.44-py3-none-any.whl.metadata (6.6 kB)
Collecting autogluon.common==1.5.0 (from autogluon.core==1.5.0->autogluon.tabular)
  Downloading autogluon_common-1.5.0-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: pyarrow<21.0.0,>=7.0.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.tabular) (18.1.0)
Requirement already satisfied: psutil<7.2.0,>=5.7.3 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.tabular) (5.9.5)
Requirement already satisfied: joblib<1.7,>=1.2 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.tabular) (1.5.3)
Requirement already satisfied: pyyaml>=5.0 in /usr/local/lib/python3.12/dist-packages (from autogluon.common==1.5.0->autogluon.core==1.5.0->autogluon.tabular) (6.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<2.4.0,>=2.0.0->autogluon.tabular) (2026.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn<1.8.0,>=1.4.0->autogluon.tabular) (3.6.0)
Collecting botocore<1.44.0,>=1.43.44 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.tabular)
  Downloading botocore-1.43.44-py3-none-any.whl.metadata (5.6 kB)
Collecting jmespath<2.0.0,>=0.7.1 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.tabular)
  Downloading jmespath-1.1.0-py3-none-any.whl.metadata (7.6 kB)
Collecting s3transfer<0.20.0,>=0.19.0 (from boto3<2,>=1.10->autogluon.core==1.5.0->autogluon.tabular)
  Downloading s3transfer-0.19.0-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular) (26.2)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<3.11,>=3.7.0->autogluon.core==1.5.0->autogluon.tabular) (3.3.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<2.4.0,>=2.0.0->autogluon.tabular) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->autogluon.core==1.5.0->autogluon.tabular) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->autogluon.core==1.5.0->autogluon.tabular) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->autogluon.core==1.5.0->autogluon.tabular) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->autogluon.core==1.5.0->autogluon.tabular) (2026.6.17)
Downloading autogluon_tabular-1.5.0-py3-none-any.whl (515 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 515.2/515.2 kB 14.2 MB/s eta 0:00:00
Downloading autogluon_core-1.5.0-py3-none-any.whl (227 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.6/227.6 kB 21.3 MB/s eta 0:00:00
Downloading autogluon_features-1.5.0-py3-none-any.whl (98 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.9/98.9 kB 11.9 MB/s eta 0:00:00
Downloading autogluon_common-1.5.0-py3-none-any.whl (74 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.4/74.4 kB 9.0 MB/s eta 0:00:00
Downloading boto3-1.43.44-py3-none-any.whl (140 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 140.0/140.0 kB 17.3 MB/s eta 0:00:00
Downloading botocore-1.43.44-py3-none-any.whl (15.4 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.4/15.4 MB 84.6 MB/s eta 0:00:00
Downloading jmespath-1.1.0-py3-none-any.whl (20 kB)
Downloading s3transfer-0.19.0-py3-none-any.whl (90 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.1/90.1 kB 6.8 MB/s eta 0:00:00
Installing collected packages: jmespath, botocore, s3transfer, boto3, autogluon.common, autogluon.features, autogluon.core, autogluon.tabular
Successfully installed autogluon.common-1.5.0 autogluon.core-1.5.0 autogluon.features-1.5.0 autogluon.tabular-1.5.0 boto3-1.43.44 botocore-1.43.44 jmespath-1.1.0 s3transfer-0.19.0

In [11]:
from autogluon.tabular import TabularDataset, TabularPredictor

# Load into AutoGluon format
train_data = TabularDataset(train_data)

# Define target column
label = "Energy Consumption"

# Train model
predictor = TabularPredictor(label=label, problem_type="regression").fit(
    train_data,
    presets="best_quality",   # higher accuracy, slower training
    time_limit=600            # 10 minutes limit
)

No path specified. Models will be saved in: "AutogluonModels/ag-20260709_054303"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.5.0
Python Version:     3.12.13
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP Thu Apr 30 18:17:14 UTC 2026
CPU Count:          2
Pytorch Version:    2.11.0+cu128
CUDA Version:       12.8
GPU Memory:         GPU 0: 14.56/14.56 GB
Total GPU Memory:   Free: 14.56 GB, Allocated: 0.00 GB, Total: 14.56 GB
GPU Count:          1
Memory Avail:       11.04 GB / 12.67 GB (87.2%)
Disk Space Avail:   65.85 GB / 112.64 GB (58.5%)
===================================================
Presets specified: ['best_quality']
Using hyperparameters preset: hyperparameters='zeroshot'
Setting dynamic_stacking from 'auto' to True. Reason: Enable dynamic_stacking when use_bag_holdout is disabled. (use_bag_holdout=False)
Stack configuration (auto_stack=True): num_stack_levels=1, num_bag_folds=8, num_bag_sets=1
DyStack is enabled (dynamic_stacking=True). AutoGluon will try to determine whether the input data is affected by stacked overfitting and enable or disable stacking as a consequence.
	This is used to identify the optimal `num_stack_levels` value. Copies of AutoGluon will be fit on subsets of the data. Then holdout validation data is used to detect stacked overfitting.
	Running DyStack for up to 150s of the 600s of remaining time (25%).
DyStack: Disabling memory safe fit mode in DyStack because GPUs were detected and num_gpus='auto' (GPUs cannot be used in memory safe fit mode). If you want to use memory safe fit mode, manually set `num_gpus=0`.
Running DyStack sub-fit ...
Beginning AutoGluon training ... Time limit = 150s
AutoGluon will save models to "/content/AutogluonModels/ag-20260709_054303/ds_sub_fit/sub_fit_ho"
Train Data Rows:    888
Train Data Columns: 6
Label Column:       Energy Consumption
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11309.18 MB
	Train Data (Original)  Memory Usage: 0.12 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 1 | ['Average Temperature']
		('int', [])    : 3 | ['Square Footage', 'Number of Occupants', 'Appliances Used']
		('object', []) : 2 | ['Building Type', 'Day of Week']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 1 | ['Building Type']
		('float', [])     : 1 | ['Average Temperature']
		('int', [])       : 3 | ['Square Footage', 'Number of Occupants', 'Appliances Used']
		('int', ['bool']) : 1 | ['Day of Week']
	0.1s = Fit runtime
	6 features in original data used to generate 6 features in processed data.
	Train Data (Processed) Memory Usage: 0.03 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.09s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 99.92s of the 149.90s of remaining time.
Will use sequential fold fitting strategy because import of ray failed. Reason: ray is required to train folds in parallel for TabularPredictor or HPO for MultiModalPredictor. A quick tip is to install via `pip install "ray>=2.43.0,<2.53.0"`
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)

[1000]	valid_set's rmse: 36.8696
[2000]	valid_set's rmse: 35.776
[3000]	valid_set's rmse: 35.3375
[4000]	valid_set's rmse: 35.068
[5000]	valid_set's rmse: 34.8496
[6000]	valid_set's rmse: 34.8009
[7000]	valid_set's rmse: 34.7197
[8000]	valid_set's rmse: 34.6405
[9000]	valid_set's rmse: 34.6021
[10000]	valid_set's rmse: 34.5805
[1000]	valid_set's rmse: 45.6394
[2000]	valid_set's rmse: 42.8481
[3000]	valid_set's rmse: 41.7737
[4000]	valid_set's rmse: 41.2672
[5000]	valid_set's rmse: 41.11
[6000]	valid_set's rmse: 41.0276
[7000]	valid_set's rmse: 40.9733
[8000]	valid_set's rmse: 40.9355
[9000]	valid_set's rmse: 40.9315
[10000]	valid_set's rmse: 40.917
[1000]	valid_set's rmse: 40.5823
[2000]	valid_set's rmse: 38.6962
[3000]	valid_set's rmse: 38.0955
[4000]	valid_set's rmse: 37.8892
[5000]	valid_set's rmse: 37.7599
[6000]	valid_set's rmse: 37.684
[7000]	valid_set's rmse: 37.6576
[8000]	valid_set's rmse: 37.651
[9000]	valid_set's rmse: 37.6402
[10000]	valid_set's rmse: 37.6315
[1000]	valid_set's rmse: 40.8767
[2000]	valid_set's rmse: 39.8821
[1000]	valid_set's rmse: 44.7738
[2000]	valid_set's rmse: 42.1473
[3000]	valid_set's rmse: 41.1696
[4000]	valid_set's rmse: 40.6234
[5000]	valid_set's rmse: 40.4336
[6000]	valid_set's rmse: 40.3226
[7000]	valid_set's rmse: 40.2303
[8000]	valid_set's rmse: 40.1633
[9000]	valid_set's rmse: 40.1273
[10000]	valid_set's rmse: 40.1001
[1000]	valid_set's rmse: 39.183
[2000]	valid_set's rmse: 37.9102
[3000]	valid_set's rmse: 37.579
[4000]	valid_set's rmse: 37.4266
[5000]	valid_set's rmse: 37.2968
[6000]	valid_set's rmse: 37.2033
[7000]	valid_set's rmse: 37.1399
[8000]	valid_set's rmse: 37.1197
[9000]	valid_set's rmse: 37.1078
[10000]	valid_set's rmse: 37.0979
[1000]	valid_set's rmse: 42.999
[2000]	valid_set's rmse: 40.8537
[3000]	valid_set's rmse: 40.4408
[4000]	valid_set's rmse: 40.1344
[5000]	valid_set's rmse: 39.9339
[6000]	valid_set's rmse: 39.8331
[7000]	valid_set's rmse: 39.7345
[8000]	valid_set's rmse: 39.6805
[9000]	valid_set's rmse: 39.6356
[10000]	valid_set's rmse: 39.6029
[1000]	valid_set's rmse: 41.0197
[2000]	valid_set's rmse: 40.2205
[3000]	valid_set's rmse: 39.9912
[4000]	valid_set's rmse: 39.9194
[5000]	valid_set's rmse: 39.8884
[6000]	valid_set's rmse: 39.8214
[7000]	valid_set's rmse: 39.8164
[8000]	valid_set's rmse: 39.7951
[9000]	valid_set's rmse: 39.7731
[10000]	valid_set's rmse: 39.7415

	-38.7424	 = Validation score   (-root_mean_squared_error)
	35.59s	 = Training   runtime
	1.04s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 56.83s of the 106.81s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)

[1000]	valid_set's rmse: 78.0993
[1000]	valid_set's rmse: 80.8163
[2000]	valid_set's rmse: 80.6355
[3000]	valid_set's rmse: 80.6184
[1000]	valid_set's rmse: 76.6612
[1000]	valid_set's rmse: 92.8995
[2000]	valid_set's rmse: 91.9301
[3000]	valid_set's rmse: 91.6062
[4000]	valid_set's rmse: 91.5553
[5000]	valid_set's rmse: 91.5394
[6000]	valid_set's rmse: 91.5328
[7000]	valid_set's rmse: 91.5274
[8000]	valid_set's rmse: 91.5237
[9000]	valid_set's rmse: 91.5216
[10000]	valid_set's rmse: 91.5204
[1000]	valid_set's rmse: 90.6843
[2000]	valid_set's rmse: 90.4928
[3000]	valid_set's rmse: 90.3977
[4000]	valid_set's rmse: 90.3532
[5000]	valid_set's rmse: 90.3324
[6000]	valid_set's rmse: 90.3263
[7000]	valid_set's rmse: 90.3206
[8000]	valid_set's rmse: 90.3163
[9000]	valid_set's rmse: 90.3144
[10000]	valid_set's rmse: 90.3133
[1000]	valid_set's rmse: 94.7711
[1000]	valid_set's rmse: 90.3266
[2000]	valid_set's rmse: 90.2143
[3000]	valid_set's rmse: 90.1473

	-85.161	 = Validation score   (-root_mean_squared_error)
	18.44s	 = Training   runtime
	0.58s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 33.65s of the 83.63s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
	-135.1304	 = Validation score   (-root_mean_squared_error)
	1.81s	 = Training   runtime
	0.14s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 31.66s of the 81.65s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Warning: Exception caused CatBoost_BAG_L1 to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 31.44s of the 81.42s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
	-111.2794	 = Validation score   (-root_mean_squared_error)
	0.72s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 30.53s of the 80.52s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	-48.5976	 = Validation score   (-root_mean_squared_error)
	12.64s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 17.71s of the 67.69s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	-106.2265	 = Validation score   (-root_mean_squared_error)
	7.86s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 9.64s of the 59.62s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Time limit exceeded... Skipping NeuralNetTorch_BAG_L1.
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 2.06s of the 52.04s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Ran out of time, early stopping on iteration 1. Best iteration is:
	[1]	valid_set's rmse: 871.992
	Time limit exceeded... Skipping LightGBMLarge_BAG_L1.
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 1.52s of the 51.50s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Warning: Exception caused CatBoost_r177_BAG_L1 to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 1.25s of the 51.23s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Not enough time to train first epoch. (Time Required: 0.09s, Time Left: 0.09s)
	Time limit exceeded... Skipping NeuralNetTorch_r79_BAG_L1.
Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 0.92s of the 50.90s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Ran out of time, early stopping on iteration 1. Best iteration is:
	[1]	valid_set's rmse: 894.18
	Time limit exceeded... Skipping LightGBM_r131_BAG_L1.
Fitting model: NeuralNetFastAI_r191_BAG_L1 ... Training model for up to 0.42s of the 50.40s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Time limit exceeded... Skipping NeuralNetFastAI_r191_BAG_L1.
Fitting model: CatBoost_r9_BAG_L1 ... Training model for up to 0.11s of the 50.09s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Warning: Exception caused CatBoost_r9_BAG_L1 to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 149.91s of the 49.75s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/10.7 GB
	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.625, 'NeuralNetFastAI_BAG_L1': 0.375}
	-31.8674	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting 106 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 49.73s of the 49.69s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)

[1000]	valid_set's rmse: 41.805
[2000]	valid_set's rmse: 41.0797
[3000]	valid_set's rmse: 41.0744
[4000]	valid_set's rmse: 41.026
[1000]	valid_set's rmse: 47.0303
[2000]	valid_set's rmse: 45.1289
[3000]	valid_set's rmse: 44.1846
[4000]	valid_set's rmse: 43.8732
[5000]	valid_set's rmse: 43.6487
[6000]	valid_set's rmse: 43.5022
[7000]	valid_set's rmse: 43.4165
[8000]	valid_set's rmse: 43.3683

	Ran out of time, early stopping on iteration 8890. Best iteration is:
	[8872]	valid_set's rmse: 43.3367

[1000]	valid_set's rmse: 46.8274
[2000]	valid_set's rmse: 44.233
[3000]	valid_set's rmse: 43.12
[4000]	valid_set's rmse: 42.5121
[5000]	valid_set's rmse: 42.1595
[6000]	valid_set's rmse: 41.969
[7000]	valid_set's rmse: 41.8376

	Ran out of time, early stopping on iteration 7978. Best iteration is:
	[7978]	valid_set's rmse: 41.7539
	Time limit exceeded... Skipping LightGBMXT_BAG_L2.
Fitting model: LightGBM_BAG_L2 ... Training model for up to 30.00s of the 29.96s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)

[1000]	valid_set's rmse: 41.7055
[1000]	valid_set's rmse: 41.94
[1000]	valid_set's rmse: 77.6393
[2000]	valid_set's rmse: 75.8763
[3000]	valid_set's rmse: 75.3275
[4000]	valid_set's rmse: 75.1811
[5000]	valid_set's rmse: 75.1467

	Ran out of time, early stopping on iteration 5546. Best iteration is:
	[5532]	valid_set's rmse: 75.1384

[1000]	valid_set's rmse: 45.2785
[2000]	valid_set's rmse: 44.4313
[3000]	valid_set's rmse: 44.1988
[1000]	valid_set's rmse: 63.0253
[2000]	valid_set's rmse: 60.3939
[3000]	valid_set's rmse: 59.9989

	-49.8601	 = Validation score   (-root_mean_squared_error)
	16.48s	 = Training   runtime
	0.29s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L2 ... Training model for up to 10.91s of the 10.88s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
	-35.9096	 = Validation score   (-root_mean_squared_error)
	2.31s	 = Training   runtime
	0.22s	 = Validation runtime
Fitting model: CatBoost_BAG_L2 ... Training model for up to 8.33s of the 8.29s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Warning: Exception caused CatBoost_BAG_L2 to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: ExtraTreesMSE_BAG_L2 ... Training model for up to 8.00s of the 7.96s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
	-34.0838	 = Validation score   (-root_mean_squared_error)
	1.46s	 = Training   runtime
	0.15s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 6.35s of the 6.31s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Ran out of time, stopping training early. (Stopping on epoch 13)
	Ran out of time, stopping training early. (Stopping on epoch 9)
	Ran out of time, stopping training early. (Stopping on epoch 5)
	Ran out of time, stopping training early. (Stopping on epoch 14)
	Ran out of time, stopping training early. (Stopping on epoch 14)
	Ran out of time, stopping training early. (Stopping on epoch 16)
	Ran out of time, stopping training early. (Stopping on epoch 18)
	Ran out of time, stopping training early. (Stopping on epoch 21)
	-107.3797	 = Validation score   (-root_mean_squared_error)
	5.93s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 149.91s of the 0.09s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/10.6 GB
	Ensemble Weights: {'LightGBMXT_BAG_L1': 0.444, 'NeuralNetFastAI_BAG_L1': 0.278, 'ExtraTreesMSE_BAG_L2': 0.278}
	-31.3862	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 149.94s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 89.3 rows/s (111 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/AutogluonModels/ag-20260709_054303/ds_sub_fit/sub_fit_ho")
Deleting DyStack predictor artifacts (clean_up_fits=True) ...
Leaderboard on holdout data (DyStack):
                     model  score_holdout   score_val              eval_metric  pred_time_test  pred_time_val   fit_time  pred_time_test_marginal  pred_time_val_marginal  fit_time_marginal  stack_level  can_infer  fit_order
0      WeightedEnsemble_L3     -19.279477  -31.386232  root_mean_squared_error        3.257840       1.625844  60.087183                 0.003116                0.000348           0.011868            3       True         12
1      WeightedEnsemble_L2     -19.921060  -31.867381  root_mean_squared_error        2.583284       1.131700  48.242743                 0.002928                0.000417           0.011871            2       True          7
2     ExtraTreesMSE_BAG_L2     -22.572016  -34.083811  root_mean_squared_error        3.254724       1.625496  60.075315                 0.124780                0.148934           1.456545            2       True         10
3        LightGBMXT_BAG_L1     -24.294610  -38.742393  root_mean_squared_error        2.461602       1.044116  35.589740                 2.461602                1.044116          35.589740            1       True          1
4   RandomForestMSE_BAG_L2     -24.642412  -35.909611  root_mean_squared_error        3.251643       1.701363  60.931402                 0.121699                0.224800           2.312631            2       True          9
5          LightGBM_BAG_L2     -34.854015  -49.860104  root_mean_squared_error        3.972700       1.764796  75.096429                 0.842757                0.288234          16.477659            2       True          8
6   NeuralNetFastAI_BAG_L1     -36.106442  -48.597627  root_mean_squared_error        0.118755       0.087167  12.641132                 0.118755                0.087167          12.641132            1       True          5
7   NeuralNetFastAI_BAG_L2     -52.461193 -107.379697  root_mean_squared_error        3.222403       1.567745  64.553501                 0.092459                0.091182           5.934731            2       True         11
8          LightGBM_BAG_L1     -64.551235  -85.160999  root_mean_squared_error        1.477162       0.577495  18.437032                 1.477162                0.577495          18.437032            1       True          2
9           XGBoost_BAG_L1     -82.041881 -106.226507  root_mean_squared_error        0.318216       0.057286   7.860618                 0.318216                0.057286           7.860618            1       True          6
10    ExtraTreesMSE_BAG_L1     -98.809187 -111.279352  root_mean_squared_error        0.108076       0.152126   0.718801                 0.108076                0.152126           0.718801            1       True          4
11  RandomForestMSE_BAG_L1    -129.967534 -135.130398  root_mean_squared_error        0.123295       0.135868   1.808479                 0.123295                0.135868           1.808479            1       True          3
	1	 = Optimal   num_stack_levels (Stacked Overfitting Occurred: False)
	157s	 = DyStack   runtime |	443s	 = Remaining runtime
Starting main fit with num_stack_levels=1.
	For future fit calls on this dataset, you can skip DyStack to save time: `predictor.fit(..., dynamic_stacking=False, num_stack_levels=1)`
Beginning AutoGluon training ... Time limit = 443s
AutoGluon will save models to "/content/AutogluonModels/ag-20260709_054303"
Train Data Rows:    1000
Train Data Columns: 6
Label Column:       Energy Consumption
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10789.48 MB
	Train Data (Original)  Memory Usage: 0.14 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', [])  : 1 | ['Average Temperature']
		('int', [])    : 3 | ['Square Footage', 'Number of Occupants', 'Appliances Used']
		('object', []) : 2 | ['Building Type', 'Day of Week']
	Types of features in processed data (raw dtype, special dtypes):
		('category', [])  : 1 | ['Building Type']
		('float', [])     : 1 | ['Average Temperature']
		('int', [])       : 3 | ['Square Footage', 'Number of Occupants', 'Appliances Used']
		('int', ['bool']) : 1 | ['Day of Week']
	0.1s = Fit runtime
	6 features in original data used to generate 6 features in processed data.
	Train Data (Processed) Memory Usage: 0.03 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.08s ...
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Large model count detected (110 configs) ... Only displaying the first 3 models of each family. To see all, set `verbosity=3`.
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}, {'activation': 'elu', 'dropout_prob': 0.10077639529843717, 'hidden_size': 108, 'learning_rate': 0.002735937344002146, 'num_layers': 4, 'use_batchnorm': True, 'weight_decay': 1.356433327634438e-12, 'ag_args': {'name_suffix': '_r79', 'priority': -2}}, {'activation': 'elu', 'dropout_prob': 0.11897478034205347, 'hidden_size': 213, 'learning_rate': 0.0010474382260641949, 'num_layers': 4, 'use_batchnorm': False, 'weight_decay': 5.594471067786272e-10, 'ag_args': {'name_suffix': '_r22', 'priority': -7}}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}, {'depth': 6, 'grow_policy': 'SymmetricTree', 'l2_leaf_reg': 2.1542798306067823, 'learning_rate': 0.06864209415792857, 'max_ctr_complexity': 4, 'one_hot_max_size': 10, 'ag_args': {'name_suffix': '_r177', 'priority': -1}}, {'depth': 8, 'grow_policy': 'Depthwise', 'l2_leaf_reg': 2.7997999596449104, 'learning_rate': 0.031375015734637225, 'max_ctr_complexity': 2, 'one_hot_max_size': 3, 'ag_args': {'name_suffix': '_r9', 'priority': -5}}],
	'XGB': [{}, {'colsample_bytree': 0.6917311125174739, 'enable_categorical': False, 'learning_rate': 0.018063876087523967, 'max_depth': 10, 'min_child_weight': 0.6028633586934382, 'ag_args': {'name_suffix': '_r33', 'priority': -8}}, {'colsample_bytree': 0.6628423832084077, 'enable_categorical': False, 'learning_rate': 0.08775715546881824, 'max_depth': 5, 'min_child_weight': 0.6294123374222513, 'ag_args': {'name_suffix': '_r89', 'priority': -16}}],
	'FASTAI': [{}, {'bs': 256, 'emb_drop': 0.5411770367537934, 'epochs': 43, 'layers': [800, 400], 'lr': 0.01519848858318159, 'ps': 0.23782946566604385, 'ag_args': {'name_suffix': '_r191', 'priority': -4}}, {'bs': 2048, 'emb_drop': 0.05070411322605811, 'epochs': 29, 'layers': [200, 100], 'lr': 0.08974235041576624, 'ps': 0.10393466140748028, 'ag_args': {'name_suffix': '_r102', 'priority': -11}}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Fitting 106 L1 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 295.28s of the 443.02s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)

[1000]	valid_set's rmse: 37.0072
[2000]	valid_set's rmse: 35.3865
[3000]	valid_set's rmse: 34.6999
[4000]	valid_set's rmse: 34.565
[5000]	valid_set's rmse: 34.5473
[6000]	valid_set's rmse: 34.5717
[1000]	valid_set's rmse: 45.2488
[2000]	valid_set's rmse: 42.4172
[3000]	valid_set's rmse: 41.3896
[4000]	valid_set's rmse: 40.8002
[5000]	valid_set's rmse: 40.5161
[6000]	valid_set's rmse: 40.2719
[7000]	valid_set's rmse: 40.1732
[8000]	valid_set's rmse: 40.1077
[9000]	valid_set's rmse: 40.0699
[10000]	valid_set's rmse: 40.0573
[1000]	valid_set's rmse: 43.5485
[2000]	valid_set's rmse: 42.4693
[3000]	valid_set's rmse: 42.2324
[1000]	valid_set's rmse: 39.0616
[2000]	valid_set's rmse: 37.8234
[3000]	valid_set's rmse: 37.5052
[4000]	valid_set's rmse: 37.3025
[5000]	valid_set's rmse: 37.2177
[6000]	valid_set's rmse: 37.1927
[7000]	valid_set's rmse: 37.1801
[8000]	valid_set's rmse: 37.1835
[1000]	valid_set's rmse: 44.7508
[2000]	valid_set's rmse: 42.0585
[3000]	valid_set's rmse: 41.1204
[4000]	valid_set's rmse: 40.7297
[5000]	valid_set's rmse: 40.587
[6000]	valid_set's rmse: 40.4572
[7000]	valid_set's rmse: 40.402
[8000]	valid_set's rmse: 40.3476
[9000]	valid_set's rmse: 40.3025
[10000]	valid_set's rmse: 40.2955
[1000]	valid_set's rmse: 48.72
[2000]	valid_set's rmse: 45.6377
[3000]	valid_set's rmse: 45.0486
[4000]	valid_set's rmse: 44.7019
[5000]	valid_set's rmse: 44.4937
[6000]	valid_set's rmse: 44.3572
[7000]	valid_set's rmse: 44.2842
[8000]	valid_set's rmse: 44.2263
[9000]	valid_set's rmse: 44.1977
[10000]	valid_set's rmse: 44.1696
[1000]	valid_set's rmse: 41.7493
[2000]	valid_set's rmse: 38.974
[3000]	valid_set's rmse: 38.017
[4000]	valid_set's rmse: 37.43
[5000]	valid_set's rmse: 37.1702
[6000]	valid_set's rmse: 37.0111
[7000]	valid_set's rmse: 36.8924
[8000]	valid_set's rmse: 36.8115
[9000]	valid_set's rmse: 36.7795
[10000]	valid_set's rmse: 36.7603
[1000]	valid_set's rmse: 43.4546
[2000]	valid_set's rmse: 41.866
[3000]	valid_set's rmse: 41.4801
[4000]	valid_set's rmse: 41.3808
[5000]	valid_set's rmse: 41.3254
[6000]	valid_set's rmse: 41.3217

	-39.6657	 = Validation score   (-root_mean_squared_error)
	31.79s	 = Training   runtime
	1.0s	 = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 256.98s of the 404.72s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)

[1000]	valid_set's rmse: 81.0282
[2000]	valid_set's rmse: 80.7769
[3000]	valid_set's rmse: 80.7377
[4000]	valid_set's rmse: 80.7165
[5000]	valid_set's rmse: 80.7132
[6000]	valid_set's rmse: 80.7122
[7000]	valid_set's rmse: 80.7113
[8000]	valid_set's rmse: 80.7109
[9000]	valid_set's rmse: 80.7107
[10000]	valid_set's rmse: 80.7106
[1000]	valid_set's rmse: 86.4267
[1000]	valid_set's rmse: 63.9597
[1000]	valid_set's rmse: 93.4366
[1000]	valid_set's rmse: 71.8142
[2000]	valid_set's rmse: 71.4529
[3000]	valid_set's rmse: 71.3881
[4000]	valid_set's rmse: 71.3533
[5000]	valid_set's rmse: 71.3434
[6000]	valid_set's rmse: 71.3417
[7000]	valid_set's rmse: 71.3418
[8000]	valid_set's rmse: 71.3432
[1000]	valid_set's rmse: 96.3454
[1000]	valid_set's rmse: 79.1497

	-81.3999	 = Validation score   (-root_mean_squared_error)
	17.13s	 = Training   runtime
	0.47s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L1 ... Training model for up to 236.79s of the 384.52s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
	-123.4069	 = Validation score   (-root_mean_squared_error)
	1.95s	 = Training   runtime
	0.22s	 = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 234.55s of the 382.29s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Warning: Exception caused CatBoost_BAG_L1 to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: ExtraTreesMSE_BAG_L1 ... Training model for up to 234.19s of the 381.93s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
	-103.4104	 = Validation score   (-root_mean_squared_error)
	0.73s	 = Training   runtime
	0.14s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 233.28s of the 381.01s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	-46.507	 = Validation score   (-root_mean_squared_error)
	7.86s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 225.27s of the 373.01s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	-97.8909	 = Validation score   (-root_mean_squared_error)
	15.95s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L1 ... Training model for up to 208.87s of the 356.60s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	-35.6264	 = Validation score   (-root_mean_squared_error)
	126.1s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 82.66s of the 230.40s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)

[1000]	valid_set's rmse: 147.763
[1000]	valid_set's rmse: 131.07
[1000]	valid_set's rmse: 120.621
[1000]	valid_set's rmse: 137.81
[2000]	valid_set's rmse: 137.809
[3000]	valid_set's rmse: 137.809
[4000]	valid_set's rmse: 137.809
[5000]	valid_set's rmse: 137.809
[6000]	valid_set's rmse: 137.809
[7000]	valid_set's rmse: 137.809
[8000]	valid_set's rmse: 137.809
[9000]	valid_set's rmse: 137.809

	Ran out of time, early stopping on iteration 9125. Best iteration is:
	[7193]	valid_set's rmse: 137.809

[1000]	valid_set's rmse: 149.643
[1000]	valid_set's rmse: 158.526
[1000]	valid_set's rmse: 150.201

	-141.8	 = Validation score   (-root_mean_squared_error)
	36.36s	 = Training   runtime
	0.55s	 = Validation runtime
Fitting model: CatBoost_r177_BAG_L1 ... Training model for up to 39.10s of the 186.84s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Warning: Exception caused CatBoost_r177_BAG_L1 to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: NeuralNetTorch_r79_BAG_L1 ... Training model for up to 38.84s of the 186.58s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Ran out of time, stopping training early. (Stopping on epoch 42)
	Ran out of time, stopping training early. (Stopping on epoch 34)
	Ran out of time, stopping training early. (Stopping on epoch 46)
	Ran out of time, stopping training early. (Stopping on epoch 49)
	Ran out of time, stopping training early. (Stopping on epoch 41)
	Ran out of time, stopping training early. (Stopping on epoch 55)
	Ran out of time, stopping training early. (Stopping on epoch 58)
	Ran out of time, stopping training early. (Stopping on epoch 65)
	-60.9012	 = Validation score   (-root_mean_squared_error)
	37.07s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBM_r131_BAG_L1 ... Training model for up to 1.66s of the 149.40s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Ran out of time, early stopping on iteration 1. Best iteration is:
	[1]	valid_set's rmse: 912.904
	Time limit exceeded... Skipping LightGBM_r131_BAG_L1.
Fitting model: NeuralNetFastAI_r191_BAG_L1 ... Training model for up to 1.11s of the 148.84s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Ran out of time, stopping training early. (Stopping on epoch 0)
	Time limit exceeded... Skipping NeuralNetFastAI_r191_BAG_L1.
Fitting model: CatBoost_r9_BAG_L1 ... Training model for up to 0.70s of the 148.44s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Warning: Exception caused CatBoost_r9_BAG_L1 to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: LightGBM_r96_BAG_L1 ... Training model for up to 0.43s of the 148.17s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Ran out of time, early stopping on iteration 1. Best iteration is:
	[1]	valid_set's rmse: 914.338
	Time limit exceeded... Skipping LightGBM_r96_BAG_L1.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.00s of the 147.59s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/10.5 GB
	Ensemble Weights: {'NeuralNetTorch_BAG_L1': 0.36, 'LightGBMXT_BAG_L1': 0.32, 'NeuralNetFastAI_BAG_L1': 0.24, 'NeuralNetTorch_r79_BAG_L1': 0.08}
	-24.4432	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting 106 L2 models, fit_strategy="sequential" ...
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 147.56s of the 147.54s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)

[1000]	valid_set's rmse: 41.3061
[2000]	valid_set's rmse: 37.5835
[3000]	valid_set's rmse: 35.9857
[4000]	valid_set's rmse: 35.1695
[5000]	valid_set's rmse: 34.6883
[6000]	valid_set's rmse: 34.4335
[7000]	valid_set's rmse: 34.2946
[8000]	valid_set's rmse: 34.1892
[9000]	valid_set's rmse: 34.1277
[10000]	valid_set's rmse: 34.0904
[1000]	valid_set's rmse: 39.3284
[2000]	valid_set's rmse: 37.5734
[3000]	valid_set's rmse: 36.7885
[4000]	valid_set's rmse: 36.4741
[5000]	valid_set's rmse: 36.2984
[6000]	valid_set's rmse: 36.1913
[7000]	valid_set's rmse: 36.101
[8000]	valid_set's rmse: 36.0623
[9000]	valid_set's rmse: 36.0364
[10000]	valid_set's rmse: 36.0199
[1000]	valid_set's rmse: 41.2152
[2000]	valid_set's rmse: 37.8078
[3000]	valid_set's rmse: 36.6189
[4000]	valid_set's rmse: 36.1604
[5000]	valid_set's rmse: 35.8991
[6000]	valid_set's rmse: 35.7768
[7000]	valid_set's rmse: 35.711
[8000]	valid_set's rmse: 35.6749
[9000]	valid_set's rmse: 35.661
[10000]	valid_set's rmse: 35.6552
[1000]	valid_set's rmse: 39.1832
[2000]	valid_set's rmse: 37.6259
[3000]	valid_set's rmse: 37.3674
[4000]	valid_set's rmse: 37.2036
[5000]	valid_set's rmse: 37.1264
[6000]	valid_set's rmse: 37.1045
[7000]	valid_set's rmse: 37.0991
[8000]	valid_set's rmse: 37.088
[9000]	valid_set's rmse: 37.0877
[10000]	valid_set's rmse: 37.0907
[1000]	valid_set's rmse: 36.7609
[2000]	valid_set's rmse: 36.1854
[3000]	valid_set's rmse: 36.0528
[4000]	valid_set's rmse: 35.8362
[5000]	valid_set's rmse: 35.735
[6000]	valid_set's rmse: 35.6929
[7000]	valid_set's rmse: 35.6464
[8000]	valid_set's rmse: 35.6432
[9000]	valid_set's rmse: 35.6285
[10000]	valid_set's rmse: 35.6215
[1000]	valid_set's rmse: 53.0011
[2000]	valid_set's rmse: 51.1816
[3000]	valid_set's rmse: 50.299
[4000]	valid_set's rmse: 49.8463
[5000]	valid_set's rmse: 49.6031
[6000]	valid_set's rmse: 49.4586
[7000]	valid_set's rmse: 49.3854
[8000]	valid_set's rmse: 49.3443
[9000]	valid_set's rmse: 49.308
[10000]	valid_set's rmse: 49.2966
[1000]	valid_set's rmse: 46.3687
[2000]	valid_set's rmse: 42.3815
[3000]	valid_set's rmse: 40.7391
[4000]	valid_set's rmse: 39.9958
[5000]	valid_set's rmse: 39.5896
[6000]	valid_set's rmse: 39.3328
[7000]	valid_set's rmse: 39.1923
[8000]	valid_set's rmse: 39.1187
[9000]	valid_set's rmse: 39.0591
[10000]	valid_set's rmse: 39.0391
[1000]	valid_set's rmse: 38.5358
[2000]	valid_set's rmse: 36.7723
[3000]	valid_set's rmse: 36.2405
[4000]	valid_set's rmse: 36.0259
[5000]	valid_set's rmse: 35.8895
[6000]	valid_set's rmse: 35.7961
[7000]	valid_set's rmse: 35.7638
[8000]	valid_set's rmse: 35.7368
[9000]	valid_set's rmse: 35.7223
[10000]	valid_set's rmse: 35.7108

	-38.0851	 = Validation score   (-root_mean_squared_error)
	47.41s	 = Training   runtime
	1.41s	 = Validation runtime
Fitting model: LightGBM_BAG_L2 ... Training model for up to 90.38s of the 90.35s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)

[1000]	valid_set's rmse: 44.543
[1000]	valid_set's rmse: 38.4092
[1000]	valid_set's rmse: 46.9952
[2000]	valid_set's rmse: 45.7912
[3000]	valid_set's rmse: 45.7162
[4000]	valid_set's rmse: 45.7048
[1000]	valid_set's rmse: 40.8208
[2000]	valid_set's rmse: 40.3605
[3000]	valid_set's rmse: 40.1734
[4000]	valid_set's rmse: 40.0638
[5000]	valid_set's rmse: 40.0068
[6000]	valid_set's rmse: 39.9879
[7000]	valid_set's rmse: 39.9758
[8000]	valid_set's rmse: 39.9637
[9000]	valid_set's rmse: 39.9617
[10000]	valid_set's rmse: 39.9607

	-38.536	 = Validation score   (-root_mean_squared_error)
	24.75s	 = Training   runtime
	0.36s	 = Validation runtime
Fitting model: RandomForestMSE_BAG_L2 ... Training model for up to 63.43s of the 63.40s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
	-23.8013	 = Validation score   (-root_mean_squared_error)
	2.36s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: CatBoost_BAG_L2 ... Training model for up to 60.89s of the 60.86s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Warning: Exception caused CatBoost_BAG_L2 to fail during training (ImportError)... Skipping this model.
		`import catboost` failed. A quick tip is to install via `pip install autogluon.tabular[catboost]==1.5.0`.
Fitting model: ExtraTreesMSE_BAG_L2 ... Training model for up to 60.62s of the 60.59s of remaining time.
	Fitting 1 model on all data (use_child_oof=True) | Fitting with cpus=2, gpus=0
	-22.0976	 = Validation score   (-root_mean_squared_error)
	0.97s	 = Training   runtime
	0.13s	 = Validation runtime
Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 59.47s of the 59.44s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	-39.8668	 = Validation score   (-root_mean_squared_error)
	8.03s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: XGBoost_BAG_L2 ... Training model for up to 51.27s of the 51.24s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	-26.7804	 = Validation score   (-root_mean_squared_error)
	5.91s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetTorch_BAG_L2 ... Training model for up to 45.25s of the 45.22s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with SequentialLocalFoldFittingStrategy (sequential: cpus=1, gpus=0)
	Ran out of time, stopping training early. (Stopping on epoch 55)
	Ran out of time, stopping training early. (Stopping on epoch 71)
	Ran out of time, stopping training early. (Stopping on epoch 70)
	Ran out of time, stopping training early. (Stopping on epoch 76)
	Ran out of time, stopping training early. (Stopping on epoch 108)
	-46.8295	 = Validation score   (-root_mean_squared_error)
	43.08s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.00s of the 1.95s of remaining time.
	Fitting 1 model on all data | Fitting with cpus=2, gpus=0, mem=0.0/10.5 GB
	Ensemble Weights: {'ExtraTreesMSE_BAG_L2': 0.48, 'RandomForestMSE_BAG_L2': 0.16, 'XGBoost_BAG_L2': 0.16, 'NeuralNetFastAI_BAG_L1': 0.08, 'LightGBMXT_BAG_L2': 0.08, 'NeuralNetTorch_BAG_L1': 0.04}
	-21.236	 = Validation score   (-root_mean_squared_error)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 441.21s ... Best model: WeightedEnsemble_L3 | Estimated inference throughput: 38.2 rows/s (125 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/AutogluonModels/ag-20260709_054303")

In [12]:
!nvidia-smi

Thu Jul  9 05:53:02 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   75C    P0             32W /   70W |     105MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|    0   N/A  N/A             532      C   /usr/bin/python3                        102MiB |
+-----------------------------------------------------------------------------------------+

In [19]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [20]:
import shutil

In [26]:
import shutil
import os

dest = "/content/drive/MyDrive/ML_projects/ENERGY_CONSUMPTION_PREDICTION_USING_AUTOGLUON/energy_consumption_model"

# Remove if it already exists
if os.path.exists(dest):
    shutil.rmtree(dest)

# Now copy fresh
shutil.copytree("/content/AutogluonModels/ag-20260709_054303", dest)

'/content/drive/MyDrive/ML_projects/ENERGY_CONSUMPTION_PREDICTION_USING_AUTOGLUON/energy_consumption_model'

In [27]:
import shutil
import os

dest = "/content/drive/MyDrive/ML_projects/ENERGY_CONSUMPTION_PREDICTION_USING_AUTOGLUON"

# Remove if it already exists
if os.path.exists(dest):
    shutil.rmtree(dest)

# Now copy fresh
shutil.copytree("/content/dataset", dest)

'/content/drive/MyDrive/ML_projects/ENERGY_CONSUMPTION_PREDICTION_USING_AUTOGLUON'

In [29]:
predictor=TabularPredictor.load("/content/drive/MyDrive/ML_projects/ENERGY_CONSUMPTION_PREDICTION_USING_AUTOGLUON/energy_consumption_prediction_model/ag-20260709_054303")

In [37]:
train_data=TabularDataset(train_data)
predictor.leaderboard(train_data, silent=True)

,model,score_test,score_val,eval_metric,pred_time_test,pred_time_val,fit_time,pred_time_test_marginal,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,LightGBMXT_BAG_L1,-5.435424,-39.665729,root_mean_squared_error,9.313091,0.996578,31.790725,9.313091,0.996578,31.790725,1,True,1
1,WeightedEnsemble_L3,-9.564293,-21.235990,root_mean_squared_error,29.725465,3.819551,295.246038,0.005730,0.000327,0.019831,3,True,18
2,ExtraTreesMSE_BAG_L2,-9.896104,-22.097580,root_mean_squared_error,16.493106,2.236055,239.545563,0.155359,0.131984,0.966483,2,True,14
3,LightGBM_BAG_L1,-11.662793,-81.399864,root_mean_squared_error,4.285740,0.466504,17.129610,4.285740,0.466504,17.129610,1,True,2
4,RandomForestMSE_BAG_L2,-12.341829,-23.801329,root_mean_squared_error,16.492936,2.239064,240.937853,0.155189,0.134993,2.358773,2,True,13
5,XGBoost_BAG_L1,-12.428933,-97.890851,root_mean_squared_error,1.094214,0.102468,15.949755,1.094214,0.102468,15.949755,1,True,6
6,XGBoost_BAG_L2,-14.699018,-26.780359,root_mean_squared_error,16.518108,2.140774,244.486469,0.180361,0.036703,5.907389,2,True,16
7,WeightedEnsemble_L2,-15.337211,-24.443200,root_mean_squared_error,10.012562,1.174705,202.828339,0.004913,0.000328,0.014861,2,True,10
8,LightGBMLarge_BAG_L1,-17.730015,-141.799954,root_mean_squared_error,5.299989,0.551080,36.362184,5.299989,0.551080,36.362184,1,True,8
9,LightGBMXT_BAG_L2,-23.156098,-38.085087,root_mean_squared_error,29.228826,3.515544,285.993562,12.891078,1.411474,47.414483,2,True,11
10,NeuralNetFastAI_BAG_L2,-24.033323,-39.866760,root_mean_squared_error,16.551856,2.175933,246.605221,0.214109,0.071863,8.026141,2,True,15
11,NeuralNetTorch_BAG_L1,-26.759274,-35.626403,root_mean_squared_error,0.107262,0.056011,126.100253,0.107262,0.056011,126.100253,1,True,7
12,LightGBM_BAG_L2,-26.979584,-38.535973,root_mean_squared_error,19.404303,2.465638,263.328444,3.066556,0.361567,24.749364,2,True,12
13,NeuralNetFastAI_BAG_L1,-31.729416,-46.507032,root_mean_squared_error,0.429304,0.062737,7.855445,0.429304,0.062737,7.855445,1,True,5
14,NeuralNetTorch_BAG_L2,-37.463375,-46.829475,root_mean_squared_error,16.472595,2.168267,281.655240,0.134848,0.064196,43.076160,2,True,17
15,ExtraTreesMSE_BAG_L1,-37.975912,-103.410432,root_mean_squared_error,0.744969,0.139430,0.732744,0.744969,0.139430,0.732744,1,True,4
16,NeuralNetTorch_r79_BAG_L1,-44.049463,-60.901163,root_mean_squared_error,0.157993,0.059051,37.067054,0.157993,0.059051,37.067054,1,True,9
17,RandomForestMSE_BAG_L1,-45.356360,-123.406900,root_mean_squared_error,0.205175,0.221292,1.953493,0.205175,0.221292,1.953493,1,True,3

In [35]:
predictions=predictor.predict(test_data.drop(columns=[label]))
print(predictions.head())

0    2872.663330
1    4283.434570
2    5102.431641
3    4642.865723
4    4827.490723
Name: Energy Consumption, dtype: float32

In [38]:
predictor.evaluate(test_data)

{'root_mean_squared_error': np.float64(-14.353773614633912),
 'mean_squared_error': -206.03081698016067,
 'mean_absolute_error': -10.849712304687454,
 'r2': 0.9996997617196383,
 'pearsonr': 0.9998634131861224,
 'median_absolute_error': np.float64(-7.699838867187509)}